"""empty message

Revision ID: af06fee9e1ce
Revises: c0ee4d4f52f2
Create Date: 2023-08-21 22:23:12.487826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af06fee9e1ce'
down_revision: Union[str, None] = 'c0ee4d4f52f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
