"""remove relations

Revision ID: b08e1b81c3ad
Revises: 3e048eb00785
Create Date: 2023-08-17 19:54:53.477454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b08e1b81c3ad'
down_revision: Union[str, None] = '3e048eb00785'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('driver_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'vehicles', 'drivers', ['driver_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.drop_column('vehicles', 'driver_id')
    # ### end Alembic commands ###
